### ISSUE TITLE
Sky View Binary Star Map

### ISSUE THREAD

**Issue by 28446** [XEphem/XEphem#96] opened 2024-05-15 16:24 UTC
Hi,
I have no "Sky View Binary Star Map" in my Menu

![xephem-4 2 0](https://github.com/XEphem/XEphem/assets/22134298/c1e3acad-e70d-43cd-9163-42de40f0ec5e)

Is this feature still present?
 

Xephem 4.2.0 build on mi own in a Debian stable.

**Comment by Jimbob-B** [comment] 2024-09-02 20:37
Yes, I think this option is working but you may need to load the additional database file named `binary_calib.edb `to see the separation plots. I purchased XEphem a long time ago and use the bundled catalogues from that edition on MacOS using the newer version executable. Selecting the double double in Lyra allows me to plot the separation of the binary system of STF2383Cc-D. You do have to select the right star to plot the binary representation.

When you right click on the binary star, you are looking for the text Visual binary to generate these separation plots.

There's another git repository for catalogs here,

[https://github.com/XEphem/Catalogs](url)

HTH

**Comment by 28446** [comment] 2024-09-07 09:38
Hi @Jimbob-B,
I have `binary_calib.edb` in `.xephem/catalogs/Official/` but in `Field stars setup` I have chose `GSC 2.2 catalog`, after all set `Local cache Directory` does not help. 

Thanks 
![immagine](https://github.com/user-attachments/assets/046d8a7a-196b-4193-a1c6-af1c7c98711e)

![immagine](https://github.com/user-attachments/assets/0ef3b595-97f4-4583-98de-9d6e515b696c)

**Comment by Jimbob-B** [comment] 2024-09-07 14:22
I'm guessing here at this functionality but when you load the `binary_calib.edb` file there are around 80 stars in that database to create the maps you are looking for. The field stars aren't used for this as far as I can see ...

I assume you can add more lines to the `binary_calib.edb` file but I don't know where to get the data from ...

**Comment by brandon-rhodes** [comment] 2024-09-12 19:46
I can confirm that the binary star map still works.

* First, I copied `binary_calib.edb` into my `~/XEphem/GUI/xephem/catalogs` directory.
* Launched XEphem.
* Opened `View` → `Sky View...`, then returned to the main window.
* Selected `Data` → `Files...`.
* Selected `Files` → `binary_calib.edb`.
* Selected `Control` → `Index...`.
* Clicked the `Binaries` radio button.
* Clicked on the first star `A 417AB`.
* Pressed the `Sky Point` button.
* Returned to the sky view, which now pointed at the star.
* Zoomed in.
* Right-clicked the star.
* From the right-click menu, selected `Show orbit...`.

And here's the window that came up.

![image](https://github.com/user-attachments/assets/3c78ff71-72d4-4aed-b367-74d5e986b56d)

Since the feature seems to work fine, I'm going to close this issue, but feel free to comment further if you think there has been a regression at some point regarding how this feature works.

**Closed by brandon-rhodes** 2024-09-12 19:46 UTC

**Comment by brandon-rhodes** [comment] 2024-09-12 19:47
(And thanks for jumping in with the help, @Jimbob-B! It was helpful to know that filename and not have to go look it up myself.)
